
server:
  port: 8761


spring:
  application:
    name: discoveryservice


eureka:
  server:
    response-cache-update-interval-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false